# docker-compose.yml
# NEW: stack backend + MySQL

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: proyecto_web
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build: ./Backend
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-mysql+pymysql://root:example@db/proyecto_web}
      USE_APSCHEDULER: ${USE_APSCHEDULER:-0}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  dbdata:
