services:
  api:
    image: sebastianmartinezpy/proyecto-web-backend:latest
    working_dir: /app/Backend
    command: ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]
    env_file: .env
    depends_on:
      - mysql_db
    ports:
      - "8000:8000"

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Coco197209
      MYSQL_DATABASE: TrabajoFinal
    ports:
      - "3310:3306"
