services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - dbdata:/var/lib/mysql

  api:
    image: sebastianmartinezpy/proyecto-web-backend:latest
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}
    ports:
      - "80:8000"   # En servidor, lo expones como puerto 80 (http)
    depends_on:
      - db

volumes:
  dbdata:

