CREATE DATABASE IF NOT EXISTS TrabajoFinal
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE TrabajoFinal;

CREATE TABLE IF NOT EXISTS items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(1000),
  image_url VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items_cleaned (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(1000),
  image_url VARCHAR(500),
  source_id INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_source
    FOREIGN KEY (source_id) REFERENCES items(id)
);
