name: CI

on:
  push:
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r Backend/requirements.txt

      - name: Smoke test imports
        shell: bash
        run: |
          python - <<'PY'
          import importlib
          for m in ["fastapi","uvicorn","sqlalchemy"]:
              importlib.import_module(m)
          print("Deps OK ✅")
          PY
