name: Docker Publish (fast)

on:
  push:
    branches: [ "main" ]
    paths:
      - "Backend/**"
      - "Backend/Dockerfile"
      - ".github/workflows/docker-publish.yml"
  workflow_dispatch:

concurrency:
  group: docker-publish
  cancel-in-progress: true

env:
  IMAGE_NAME: proyecto-web-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Show tag that will be pushed
        run: echo "Pushing tag -> ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

      - name: Build & Push (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Backend/Dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
